"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['./MSR605 Card Reader Writer.py']
DATA_FILES = ['--iconfile']
OPTIONS = {'iconfile': '/Users/admin/MSR605-GUI/msr.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
